- name: Configurar ACR e imágenes
  hosts: localhost
  vars_files: 
    - credentials.yml
  tasks:
    - name: Extraer, construir, etiquetar y enviar imágenes a ACR
      include_role:
        name: acr

- name: Configurar servidor web
  hosts: vm
  vars_files: 
    - credentials.yml
  tasks:
    - name: Configurar VM con Podman y desplegar servidor web
      include_role:
        name: vm

- name: Configurar AKS
  hosts: localhost
  vars_files: 
    - credentials.yml
  tasks:
    - name: Desplegar aplicación en AKS
      include_role:
        name: aks
